version: '3.8'

services:
  flask:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - flask-data:/app/data
    networks:
      - flask-network

networks:
  flask-network:
    driver: bridge

volumes:
  flask-data:
    driver: local
